### ISSUE TITLE
Name method conflicts with ZenTest

### ISSUE THREAD

**Issue by jbhannah** [binarylogic/settingslogic#11]
When using Spork, RSpec, and Cucumber with a Rails project that uses Settingslogic, trying to start Spork causes the following error:

```
No such file or directory - No file specified as Settingslogic source (Errno::ENOENT)
/Library/Ruby/Gems/1.8/gems/settingslogic-2.0.6/lib/settingslogic.rb:101:in `initialize'
/Library/Ruby/Gems/1.8/gems/settingslogic-2.0.6/lib/settingslogic.rb:63:in `new'
/Library/Ruby/Gems/1.8/gems/settingslogic-2.0.6/lib/settingslogic.rb:63:in `instance'
/Library/Ruby/Gems/1.8/gems/settingslogic-2.0.6/lib/settingslogic.rb:10:in `name'
/Library/Ruby/Gems/1.8/gems/ZenTest-4.3.2/lib/ZenTest.rb:4
/Library/Ruby/Gems/1.8/gems/ZenTest-4.3.2/lib/ZenTest.rb:3:in `each_object'
```

This appears to be because the "name" method called by ZenTest conflicts with a Settingslogic method, which causes Settingslogic to throw an error. This appears to be fixed[1] by mtarnovan's fork of Settingslogic by just removing the method; can we have this or an equivalent change made in this branch, and have a new version of the gem made available that includes this fix?

[1]http://github.com/mtarnovan/settingslogic/commit/b21e9fa6b8f02d77e2a199437dffe46c8bf0d085

**Comment by benlangfeld** [comment]
I'm seeing this also

**Comment by benlangfeld** [comment]
Any chance this could be merged?

**Comment by agibralter** [comment]
+1

**Comment by agibralter** [comment]
I guess for the time being, you can just put `gem "settingslogic"` after `gem "ZenTest"` and it works.
