### ISSUE TITLE
suggestion: I18n awareness

### ISSUE THREAD

**Issue by grimen** [binarylogic/settingslogic#6]
....take I18n.locale into account. Seems to be tricky to setup now.

**Comment by bergman** [comment]
Are you trying to set the namespace to I18n.locale? That's what I'm trying to do and I get this:

Error message:

```
can't convert nil into Hash
```

Stack trace:

```
/Library/Ruby/Gems/1.8/gems/settingslogic-2.0.6/lib/settingslogic.rb:107:in `replace'
/Library/Ruby/Gems/1.8/gems/settingslogic-2.0.6/lib/settingslogic.rb:107:in `initialize'
/Library/Ruby/Gems/1.8/gems/settingslogic-2.0.6/lib/settingslogic.rb:63:in `new'
/Library/Ruby/Gems/1.8/gems/settingslogic-2.0.6/lib/settingslogic.rb:63:in `instance'
/Library/Ruby/Gems/1.8/gems/settingslogic-2.0.6/lib/settingslogic.rb:40:in `[]'
```

**EDIT:**

This works:

```
namespace I18n.locale.to_s
```
